language: python
python:
  - 3.6
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: 
  - flake8
  - travis_wait 30 python run.py --train --goal tracking
  - python run.py --goal tracking
  - python -m pytest tests/test_*.py
  - python -m bugbug.bug_snapshot
  - python setup.py sdist
  - pip install dist/bugbug-$(cat VERSION).tar.gz
